site_name: Loopring Documentation
theme: readthedocs
strict: true
repo_url: https://github.com/Loopring/documents
site_description: Loopring - Decentralized Token Exchange Protocol
pages:
    - About: index.md
    - Overview: overview.md
    - LRC Token: token.md
    - Projects:
        - 'Protocol': projects/protocol.md
        - 'Relays': projects/relay.md
        - 'Ring Miners': projects/ringminer.md
        - 'Wallets': projects/wallet.md
        - 'Tokenization Services': projects/tokenization.md
    - Contribution: contribution.md