site_name: Loopring Documentation
theme: readthedocs
strict: true
repo_url: https://github.com/Loopring/documents
site_description: Loopring - Decentralized Token Exchange Protocol
pages:
    - About: index.md
    - Protocol Smart-Contract:
        - 'Overview': protocol/overview.md
        - 'Roles': protocol/roles.md
        - 'Order-Rings': protocol/ring.md
        - 'Fee Model': protocol/fee.md
        - 'Pricing': protocol/pricing.md
    - Other Sub-Projects:
        - 'Overview': projects/overview.md
        - 'Relayer': projects/relayer.md
        - 'Ring Miner': projects/ringminer.md
        - 'Wallet': projects/wallet.md
    - Community:
        - 'How to contribute': community/how-to-contribute.md
        - 'Contributors': community/contributors.md